product:
  property: Product Profile Dev

spring:
  data:
    mongodb:
      uri: mongodb+srv://ipraetoriux:741963@cluster0.5w8juwv.mongodb.net/test
      database: test

app:
  testProp: Esto ha sido actualizado con Actuator @RefreshScope